[phases.setup]
nixPkgs = ['php84', 'php84Packages.composer', 'php84Extensions.pdo_mysql', 'php84Extensions.mbstring', 'php84Extensions.xml', 'php84Extensions.gd', 'php84Extensions.fileinfo']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev']

[start]
cmd = 'sh start.sh'
